spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  profiles:
    default: deploy
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/master.xml